# Copyright 2021 Google LLC

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     https://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: A workflow for updating discovery artifacts
# Controls when the action will run.

on:
  # For testing purposes
  # Triggers the workflow on pull request events but only for the master branch
  pull_request:
    branches: [ master ]

  # Schedule to run every day at 2 AM.
  schedule:
    - cron:  '0 2 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Update Discovery Artifacts PR
    runs-on: ubuntu-latest
    if: |
      ${{github.event.pull_request.user.login == 'parthea' && github.event.pull_request.title == 'chore: Add github action to update discovery artifacts'}}
    steps:
      - name: Check out working directory for changes
        uses: actions/checkout@v2
        with:
          ref: refs/heads/master
          path: ./branch

      - name: Check out branch with scripts
        uses: actions/checkout@v2
        with:
          ref: refs/heads/add-github-action-to-update-discovery-artifacts
          path: ./branch_with_scripts

      - name: Check out master
        uses: actions/checkout@v2
        with:
          ref: refs/heads/master
          path: ./main

      - name: Create branch
        run: |
          git checkout -b update-discovery-artifacts
        working-directory: ./branch

      - name: Clone discovery artifacts from discovery-artifact manager
        uses: actions/checkout@v2
        with:
          repository: googleapis/discovery-artifact-manager
          path: ./discovery-artifact-manager

      - name: Copy scripts
        run: |
          cp ../branch_with_scripts/scripts/* .
        working-directory: ./branch

      - name: Copy discovery artifacts
        run: |
          cp ../discovery-artifact-manager/discoveries/*.json googleapiclient/discovery_cache/documents/
        working-directory: ./branch

      - name: Get changed discovery artifacts
        run: git diff origin/master --name-only -- '*.json' |
              sed 's/.*\///' > changed_files
        working-directory: ./branch

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip3 install -r requirements.txt
        working-directory: ./branch

      - name: Install google-api-python-client
        run: pip3 install -e .
        working-directory: ./branch

      # Apply a workaround to discovery.py to avoid DefaultCredentialsError
      # which is raised when calling `build_from_document()` as a result of
      # `google.auth.default()`. The workaround is to bypass the code block that
      # attempts to load default credentials.
      - name: Workaround to avoid DefaultCredentialsError in discovery.py
        run: sed -i -e 's/if credentials is None/if False/g' googleapiclient/discovery.py
        working-directory: ./branch

      - name: Update the docs
        run: python3 describe.py
        working-directory: ./branch

      - name: Run Change Summary
        run: python3 changesummary.py
        working-directory: ./branch

      - name: Commit changes
        run: ./createcommits.sh
        working-directory: ./branch

      - name: Push changes
        run: git push -f --set-upstream origin update-discovery-artifacts
        working-directory: ./branch

      - name: Prepare summary for PR Body
        id: pr_body
        shell: bash
        run: |
          python3 buildprbody.py
          output=$(cat temp/allapis.summary)
          output="${output//'%'/'%25'}"
          output="${output//$'\n'/'%0A'}"
          output="${output//$'\r'/'%0D'}"
          echo "::set-output name=change_summary::$output"
        working-directory: ./branch

      - name: Create PR
        uses: actions/github-script@v2.0.0
        with:
          github-token: ${{secrets.YOSHI_CODE_BOT_TOKEN}}
          script: |
            async function createPR () {
              const { owner, repo } = context.repo
              const branch = 'update-discovery-artifacts'
              let prBody = `${{ steps.pr_body.outputs.change_summary }}`
              const prTitle = 'chore: Update discovery artifacts'
              const pullRequests = await github.pulls.list({
                owner: owner,
                repo: repo,
                head: `${owner}:${branch}`,
                state: 'open'
              })

              if (pullRequests.data.length === 1) {
                prNumber = pullRequests.data[0].number
                await github.pulls.update({
                  owner: owner,
                  repo: repo,
                  pull_number: prNumber,
                  title: prTitle,
                  body: prBody
                })
                console.log('Updated PR')
              } else {
                const createPrResult = await github.pulls.create({
                  owner: owner,
                  repo: repo,
                  base: 'master',
                  head: `${owner}:${branch}`,
                  title: prTitle,
                  body: prBody
                })
                prNumber = createPrResult.data.number
                console.log('Created PR')
              }
            }
            createPR()
